#!/usr/bin/env node
// build_catalog.mjs -- generate components/index.js and components/CATALOG.md from each component's meta.
//   node build_catalog.mjs            write both
//   node build_catalog.mjs --check    exit 1 if either is stale
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const COMP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'components');
const GROUPS = [['controls', 'Controls'], ['feedback', 'Feedback'], ['data', 'Data and content'], ['chrome', 'App chrome']];

export async function collect() {
  const out = [];
  for (const [g] of GROUPS) {
    const dir = path.join(COMP, g);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter((f) => f.endsWith('.js')).sort()) {
      const mod = await import(pathToFileURL(path.join(dir, f)).href);
      if (mod.meta.name !== f.replace(/\.js$/, '')) throw new Error(`${g}/${f}: meta.name must be "${f.replace(/\.js$/, '')}"`);
      if (mod.meta.group !== g) throw new Error(`${g}/${f}: meta.group must be "${g}"`);
      out.push({ group: g, file: `${g}/${f}`, meta: mod.meta });
    }
  }
  return out;
}

export function indexJs(list) {
  const id = (n) => n.replace(/-(\w)/g, (_, c) => c.toUpperCase());
  return ['// GENERATED by scripts/build_catalog.mjs -- do not edit.',
    "export { createScene } from './core/engine.js';",
    ...list.map((c) => `import * as ${id(c.meta.name)} from './${c.file}';`),
    `export const registry = {\n${list.map((c) => `  '${c.meta.name}': ${id(c.meta.name)},`).join('\n')}\n};`, ''].join('\n');
}

// A table cell: a bare | would end the cell (enum types are a|b|c), so escape it.
const cell = (s) => String(s).replace(/\|/g, '\\|');

export function catalogMd(list) {
  const L = ['# Component catalog', '', '<!-- GENERATED by scripts/build_catalog.mjs from each component\'s meta. Do not edit; run the script. -->', '',
    'Name a component in a `states()` row with `use:` and pass its props as keys. Aim the cursor at a hotspot with `target:`.',
    'Any row can also carry `shake: true` (error shake on arrival) and `badge: <n>` (a count bubble on the shape).', '',
    '```js', "{ at: 4, use: 'toast', text: 'Exported' }            // states()", "{ at: 3.5, target: 'toast', press: true }             // cursor()", '```', ''];
  for (const [g, title] of GROUPS) {
    const items = list.filter((c) => c.group === g);
    if (!items.length) continue;
    L.push(`## ${title}`, '', items.map((c) => `[${c.meta.name}](#${c.meta.name})`).join(' · '), '');
    for (const { meta: m } of items) {
      L.push(`### ${m.name}`, '', `![${m.name}](docs-images/${m.name}.png)`, '', `**Use when:** ${m.useWhen}`, '', `**Motion:** ${m.motion}`, '',
        '| Prop | Type | Default |', '|---|---|---|',
        ...Object.entries(m.props).map(([k, [ty, def]]) => `| \`${k}\` | \`${cell(ty)}\` | \`${cell(JSON.stringify(def))}\` |`), '',
        `**Hotspots:** ${m.hotspots.map((h) => `\`${h}\``).join(', ') || 'none'}  `, `**Sounds:** ${m.sounds.join(', ') || 'none'}`, '',
        '```js', m.example, '```', '');
    }
  }
  return L.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const list = await collect();
  const files = { 'index.js': indexJs(list), 'CATALOG.md': catalogMd(list) };
  if (process.argv.includes('--check')) {
    const stale = Object.entries(files).filter(([f, s]) => !existsSync(path.join(COMP, f)) || readFileSync(path.join(COMP, f), 'utf8') !== s).map(([f]) => f);
    // The catalog shows each component's thumbnail, so a missing one is stale too.
    stale.push(...list.map((c) => `docs-images/${c.meta.name}.png`).filter((f) => !existsSync(path.join(COMP, f))));
    if (stale.length) { console.error(`stale: ${stale.join(', ')} (run node scripts/build_catalog.mjs && node scripts/gallery.mjs "" --stills)`); process.exit(1); }
    console.log(`catalog up to date (${list.length} components)`);
  } else {
    for (const [f, s] of Object.entries(files)) writeFileSync(path.join(COMP, f), s);
    console.log(`wrote index.js and CATALOG.md (${list.length} components)`);
  }
}
