// GENERATED by scripts/build_catalog.mjs -- do not edit.
export { createScene } from './core/engine.js';
import * as button from './controls/button.js';
import * as checkbox from './controls/checkbox.js';
import * as dropdown from './controls/dropdown.js';
import * as input from './controls/input.js';
import * as slider from './controls/slider.js';
import * as tabs from './controls/tabs.js';
import * as toggle from './controls/toggle.js';
export const registry = {
  'button': button,
  'checkbox': checkbox,
  'dropdown': dropdown,
  'input': input,
  'slider': slider,
  'tabs': tabs,
  'toggle': toggle,
};
