// GENERATED by scripts/build_catalog.mjs -- do not edit.
export { createScene } from './core/engine.js';
import * as button from './controls/button.js';
import * as checkbox from './controls/checkbox.js';
import * as dropdown from './controls/dropdown.js';
import * as input from './controls/input.js';
import * as slider from './controls/slider.js';
import * as tabs from './controls/tabs.js';
import * as toggle from './controls/toggle.js';
import * as check from './feedback/check.js';
import * as loader from './feedback/loader.js';
import * as progress from './feedback/progress.js';
import * as status from './feedback/status.js';
import * as toast from './feedback/toast.js';
export const registry = {
  'button': button,
  'checkbox': checkbox,
  'dropdown': dropdown,
  'input': input,
  'slider': slider,
  'tabs': tabs,
  'toggle': toggle,
  'check': check,
  'loader': loader,
  'progress': progress,
  'status': status,
  'toast': toast,
};
