// GENERATED by scripts/build_catalog.mjs -- do not edit.
export { createScene } from './core/engine.js';
import * as button from './controls/button.js';
export const registry = {
  'button': button,
};
